---
title: "課?<a0>?練習模<e7><89><88>"
author: "?B????"
date: "2020-10-14"
output: output_format
params:
  id: "410884003"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
"\u0928\u092e\u0938\u094d\u0924\u0947 \u0926\u0941\u0928\u093f\u092f\u093e"
```
```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

typeof(num)
typeof(int)
typeof(char)
typeof(logi)
```
```{r}
class(num)
class(int)
class(char)
class(logi)
```
```{r}
"1"+"1.5"
```
## factor
```{r}
# 10位學生的主系
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)
#or
majors10_factor <- factor(majors10_char)
typeof(majors10_factor)
class(majors10_factor)
```
```{r haha}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```
```{r}
# 10位學生的主系
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)
#or
majors10_factor <- factor(majors10_char)
typeof(majors10_factor)
class(majors10_factor)
```
```{r}
char3 <- c("小明","1","3")
as.integer(char3)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
stringInteger+2
```

### markdown(heading)level3

```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
typeof(trueInteger)
trueInteger+2
```
```{r}
char3 <- c("小明","1","3")
as.integer(char3)
```
```{r}
studentId <- c(410773002, 410773015)
```

```{r}
as.integer(stringInteger)
class(stringInteger)
```

